

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
ZMQ = "c2297ded-f4af-51ae-bb23-16f91089e4e1"
MsgPack = "99f44e22-a591-53d1-9472-aa23ef4bd671"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.10"
ForwardDiff = "0.10"
ZMQ = "1.2"
MsgPack = "1.2"
HDF5 = "0.17"
