[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
ZMQ = "c2297ded-f4af-51ae-bb23-16f91089e4e1"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
